// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.30.0--dev
// source: content_size.proto

package indexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *uint64            `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Unit  *UnitOfInformation `protobuf:"varint,2,opt,name=unit,enum=griot.content.index.UnitOfInformation" json:"unit,omitempty"`
}

func (x *ContentSize) Reset() {
	*x = ContentSize{}
	mi := &file_content_size_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSize) ProtoMessage() {}

func (x *ContentSize) ProtoReflect() protoreflect.Message {
	mi := &file_content_size_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSize.ProtoReflect.Descriptor instead.
func (*ContentSize) Descriptor() ([]byte, []int) {
	return file_content_size_proto_rawDescGZIP(), []int{0}
}

func (x *ContentSize) GetValue() uint64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *ContentSize) GetUnit() UnitOfInformation {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return UnitOfInformation_BIT
}

var File_content_size_proto protoreflect.FileDescriptor

var file_content_size_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x67, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x19, 0x75, 0x6e, 0x69, 0x74, 0x5f,
	0x6f, 0x66, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x75, 0x6e, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x67, 0x72, 0x69, 0x6f, 0x74, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x55, 0x6e,
	0x69, 0x74, 0x4f, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x35, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x67, 0x72, 0x69, 0x6f, 0x74,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x70, 0x62, 0x3b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x70,
	0x62, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
}

var (
	file_content_size_proto_rawDescOnce sync.Once
	file_content_size_proto_rawDescData = file_content_size_proto_rawDesc
)

func file_content_size_proto_rawDescGZIP() []byte {
	file_content_size_proto_rawDescOnce.Do(func() {
		file_content_size_proto_rawDescData = protoimpl.X.CompressGZIP(file_content_size_proto_rawDescData)
	})
	return file_content_size_proto_rawDescData
}

var file_content_size_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_content_size_proto_goTypes = []any{
	(*ContentSize)(nil),    // 0: griot.content.index.ContentSize
	(UnitOfInformation)(0), // 1: griot.content.index.UnitOfInformation
}
var file_content_size_proto_depIdxs = []int32{
	1, // 0: griot.content.index.ContentSize.unit:type_name -> griot.content.index.UnitOfInformation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_content_size_proto_init() }
func file_content_size_proto_init() {
	if File_content_size_proto != nil {
		return
	}
	file_unit_of_information_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_content_size_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_size_proto_goTypes,
		DependencyIndexes: file_content_size_proto_depIdxs,
		MessageInfos:      file_content_size_proto_msgTypes,
	}.Build()
	File_content_size_proto = out.File
	file_content_size_proto_rawDesc = nil
	file_content_size_proto_goTypes = nil
	file_content_size_proto_depIdxs = nil
}
