// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.30.0--dev
// source: unit_of_information.proto

package indexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnitOfInformation int32

const (
	UnitOfInformation_BIT  UnitOfInformation = 0
	UnitOfInformation_BYTE UnitOfInformation = 1
)

// Enum value maps for UnitOfInformation.
var (
	UnitOfInformation_name = map[int32]string{
		0: "BIT",
		1: "BYTE",
	}
	UnitOfInformation_value = map[string]int32{
		"BIT":  0,
		"BYTE": 1,
	}
)

func (x UnitOfInformation) Enum() *UnitOfInformation {
	p := new(UnitOfInformation)
	*p = x
	return p
}

func (x UnitOfInformation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitOfInformation) Descriptor() protoreflect.EnumDescriptor {
	return file_unit_of_information_proto_enumTypes[0].Descriptor()
}

func (UnitOfInformation) Type() protoreflect.EnumType {
	return &file_unit_of_information_proto_enumTypes[0]
}

func (x UnitOfInformation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitOfInformation.Descriptor instead.
func (UnitOfInformation) EnumDescriptor() ([]byte, []int) {
	return file_unit_of_information_proto_rawDescGZIP(), []int{0}
}

var File_unit_of_information_proto protoreflect.FileDescriptor

var file_unit_of_information_proto_rawDesc = []byte{
	0x0a, 0x19, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x6f, 0x66, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x67, 0x72, 0x69,
	0x6f, 0x74, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x2a, 0x26, 0x0a, 0x11, 0x55, 0x6e, 0x69, 0x74, 0x4f, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x49, 0x54, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x42, 0x59, 0x54, 0x45, 0x10, 0x01, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x35, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x67, 0x72,
	0x69, 0x6f, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x70, 0x62, 0x3b, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x70, 0x62, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8,
	0x07,
}

var (
	file_unit_of_information_proto_rawDescOnce sync.Once
	file_unit_of_information_proto_rawDescData = file_unit_of_information_proto_rawDesc
)

func file_unit_of_information_proto_rawDescGZIP() []byte {
	file_unit_of_information_proto_rawDescOnce.Do(func() {
		file_unit_of_information_proto_rawDescData = protoimpl.X.CompressGZIP(file_unit_of_information_proto_rawDescData)
	})
	return file_unit_of_information_proto_rawDescData
}

var file_unit_of_information_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_unit_of_information_proto_goTypes = []any{
	(UnitOfInformation)(0), // 0: griot.content.index.UnitOfInformation
}
var file_unit_of_information_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_unit_of_information_proto_init() }
func file_unit_of_information_proto_init() {
	if File_unit_of_information_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unit_of_information_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unit_of_information_proto_goTypes,
		DependencyIndexes: file_unit_of_information_proto_depIdxs,
		EnumInfos:         file_unit_of_information_proto_enumTypes,
	}.Build()
	File_unit_of_information_proto = out.File
	file_unit_of_information_proto_rawDesc = nil
	file_unit_of_information_proto_goTypes = nil
	file_unit_of_information_proto_depIdxs = nil
}
