name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

        - name: Mount Bazel cache
          uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
          with:
            path: |
              ~/.cache/bazel
            key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
            restore-keys: |
              ${{ runner.os }}-bazel-

        - name: Fetch dependencies
          run: bazel fetch //...
  
        - name: Build
          run: bazel build //...
  
        - name: Test
          run: bazel test //...

        - name: Login to GitHub Container Registry
          uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and publish images
          run: |
            tarballTargets=$(bazel query "kind(filegroup, //...)" | grep ".tar$")
            while IFS=';' read -ra tarballs; do
            for tarball in "${tarballs[@]}"; do
                bazel build $tarball
                tarFiles=$(bazel cquery --noshow_progress --ui_event_filters=-info,-stderr --output=files $tarball)
                img=$(docker load -q --input $tarFiles)
                imgWithTag=${img#"Loaded image: "}
                imgAndTag=(${imgWithTag//:/ })
                img=${imgAndTag[0]}
                tag=${imgAndTag[1]}
                docker tag $imgWithTag "$img:${{ github.event.release.tag_name }}"
                docker push -a $img
            done
            done <<< "$tarballTargets"